server:
  port: 8080
  contextPath: /
---
app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000
spring:
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    open-in-view: false
  profiles: local,default
  data:
    rest:
      base-path: api
datasource:
  sampleapp:
    url: jdbc:postgresql://127.0.0.1:5432/words
    username: user
    password: pass
    driverClassName: org.postgresql.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: validate
      show_sql: false
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQL9Dialect
orika:
  # Whether to enable auto-configuration.
  # Defaults to true.
  enabled: true
  # Whether to use built-in converters (MapperFactoryBuilder#useBuiltinConverters(boolean)).
  # Follows Orika's behavior by default.
  useBuiltinConverters: true
  # Whether to use auto-mapping (MapperFactoryBuilder#useAutoMapping(boolean)).
  # Follows Orika's behavior by default.
  useAutoMapping: true
  # Whether to map null values (MapperFactoryBuilder#mapNulls(boolean)).
  # Follows Orika's behavior by default.
  mapNulls: true
  # Whether to dump the current state of the mapping infrastructure objects
  # upon occurrence of an exception while mapping (MapperFactoryBuilder#dumpStateOnException(boolean)).
  # Follows Orika's behavior by default.
  dumpStateOnException: false
  # Whether the class-map should be considered 'abstract' (MapperFactoryBuilder#favorExtension(boolean)).
  # Follows Orika's behavior by default.
  favorExtension: false
  # Whether full field context should be captured (MapperFactoryBuilder#captureFieldContext(boolean)).
  # Follows Orika's behavior by default.
  captureFieldContext: false

